---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-promox-lbctl
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  tls.key: {{ .Values.lbmanager.tls.key | b64enc | quote }}
  tls.crt: {{ .Values.lbmanager.tls.cert | b64enc | quote }}
  ca.crt: {{ .Values.lbmanager.tls.caCert | b64enc | quote  }}
  proxmoxToken: {{ .Values.proxmox.apiToken  | b64enc | quote }}
  proxmoxUser: {{ .Values.proxmox.user  | b64enc | quote }}
  proxmoxCA.crt: {{ .Values.proxmox.caCert  | b64enc | quote }}

